apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-app
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://github.com/k4shE/argocd-config.git
      targetRevision: HEAD
      path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
