apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: web-container
          image: k4she/wtf
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-test
  labels:
    app: vault-app
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: vault-app
    template:
      metadata:
        labels:
          app: vault-app
      spec:
        containers:
          - name: vault-container
            image: hashicorp/vault
            ports:
              - containerPort: 80