apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: web-container
          image: k4she/wtf
          ports:
            - containerPort: 80
